# Kubernetes Event Exporter Helm values
# Override broken default Bitnami image
image:
  registry: ghcr.io
  repository: resmoio/kubernetes-event-exporter
  tag: v1.7

config:
  logFormat: json
  receivers:
    - name: dump
      stdout: {}
  route:
    routes:
      - match:
          - receiver: dump
