---
all:
  vars:
    cluster_name: "k8s"
    cluster_endpoint: "https://192.168.122.100:6443"
    haproxy_ip: "192.168.122.100"
    metallb_pool_range: "192.168.122.200-192.168.122.230"
    gateway: "192.168.122.1"
    dns_server: "192.168.122.1"
    talos_config_dir: "{{ playbook_dir }}/../talos-generated"

  children:
    haproxy:
      hosts:
        haproxy-01:
          ansible_host: "192.168.122.100"
          ansible_user: alpine
          ansible_become: true
          ansible_become_method: doas
          ansible_connection: ssh

    controlplane:
      vars:
        ansible_connection: local
      hosts:
        cp-1:
          ansible_host: "192.168.122.101"
          node_ip: "192.168.122.101"
        cp-2:
          ansible_host: "192.168.122.102"
          node_ip: "192.168.122.102"
        cp-3:
          ansible_host: "192.168.122.103"
          node_ip: "192.168.122.103"

    workers:
      vars:
        ansible_connection: local
      hosts:
        worker-1:
          ansible_host: "192.168.122.104"
          node_ip: "192.168.122.104"
        worker-2:
          ansible_host: "192.168.122.105"
          node_ip: "192.168.122.105"
        worker-3:
          ansible_host: "192.168.122.106"
          node_ip: "192.168.122.106"
