apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      targetRevision: 0.35.1
      helm:
        valueFiles:
          - $values/k8s/descheduler/values.yaml
    - repoURL: https://github.com/hassansallam/home-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
