apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: kubernetes-event-exporter
      targetRevision: 3.4.5
      helm:
        valueFiles:
          - $values/k8s/event-exporter/values.yaml
    - repoURL: git@github.com:hassansallam/home-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
