apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  sources:
    - repoURL: https://charts.deliveryhero.io
      chart: node-problem-detector
      targetRevision: 2.3.14
      helm:
        valueFiles:
          - $values/k8s/node-problem-detector/values.yaml
    - repoURL: git@github.com:hassansallam/home-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
