apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts
      chart: trivy-operator
      targetRevision: 0.32.1
      helm:
        valueFiles:
          - $values/k8s/trivy-operator/values.yaml
    - repoURL: https://github.com/hassansallam/home-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
