---
- name: Fetch kubeconfig
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Get kubeconfig from Talos
      command: >
        talosctl kubeconfig {{ kubeconfig_path }}
        --nodes {{ hostvars[groups['controlplane'][0]]['node_ip'] }}
        --talosconfig {{ talos_config_dir }}/talosconfig
        --force
