grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: true

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false
