admissionController:
  replicas: 1
  container:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

backgroundController:
  enabled: true

cleanupJobs:
  admissionReports:
    image:
      tag: "1.31.0"
  clusterAdmissionReports:
    image:
      tag: "1.31.0"

features:
  forceFailurePolicyIgnore:
    enabled: true
